spring.application.name=transaction-service
server.port=8085
jwt.secret=change-me-change-me-change-me-change-me
spring.datasource.url=jdbc:h2:file:./transaction-database
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
