server:
  port: 8083

jwt:
  secret: "change-me-change-me-change-me-change-me"

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9001
          predicates:
            - Path=/auth/**

        - id: transaction-service-by-account
          uri: http://localhost:8085
          predicates:
            - Path=/api/accounts/*/transactions

        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**

        - id: client-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/clients/**
